function logPost = getlogPostQonly(parsQonly,...
                                   EX_Qonly,...
                                   VAR_Qonly,...
                                   EX_Sigma_cP,...
                                   VAR_Sigma_cP,...
                                   Y,W,cP,mats,dt,kinfQ,K1Q_X,lam0,lam1,Sigma_cP,sige,...
                                   varargin)
% This function calculates log posterior density as sum of model log
% likelihood and univariate log N(EX,VAR) prior densities

% tempering
if isempty(varargin)
    fi = 1;
else
    fi = varargin{1};
end

% log posterior density
logPost = getLlk(Y(1:end-1,:),W,cP(1:end-1,:),mats,dt,kinfQ,K1Q_X,lam0,lam1,Sigma_cP,sige) ...
    + getLlk1(Y(end,:),W,cP(end-1:end,:),mats,dt,kinfQ,K1Q_X,lam0,lam1,Sigma_cP,sige)*fi ...
    + uvnlogPrior(parsQonly,EX_Qonly,VAR_Qonly) ...
    + uvnlogPrior(Sigma_cP2pars(logd(Sigma_cP)),EX_Sigma_cP,VAR_Sigma_cP);

end